### ISSUE TITLE
CPANRatings is read-only - remove from suggestions on Contribute page.

### ISSUE THREAD

**Issue by dwwalker** [PerlDancer/perldancer-website#50]
The "Contribute" page at <http://www.perldancer.org/contribute> suggests making a rating at <http://cpanratings.perl.org/dist/Dancer2> but CPANRatings is now read-only and cannot be used for new ratings anymore.

**Comment by cromedome** [comment]
Posted #51 to address. Thanks for reporting!

**Comment by cromedome** [comment]
Merged. Closing!
