### ISSUE TITLE
"gen" subcommand missing from Quickstart guide?

### ISSUE THREAD

**Issue by bonifex** [PerlDancer/perldancer-website#60]
The Quickstart guide says do the following to scaffold a new Dancer2 application:

`$ dancer2 -a MyWeb::App`

Shouldn't this be:

`$ dancer2 gen -a MyWeb::App`

**Comment by cromedome** [comment]
You are correct! I'll try to get this resolved soon. Thanks for bringing it to our attention.

**Comment by cromedome** [comment]
Done. Thanks!
