### ISSUE TITLE
Link for "Download stable release" on home page is missing

### ISSUE THREAD

**Issue by bonifex** [PerlDancer/perldancer-website#61]
The "Download stable release" image on the home page has an empty href, so clicking on it has no effect.

**Comment by bigpresh** [comment]
Hmm, yes, something appears to have gone wrong there, thanks for letting us know!

**Comment by bigpresh** [comment]
I think we need to pull (and cache) info on the latest release from the MetaCPAN API e.g. https://fastapi.metacpan.org/v1/release/Dancer2 and pass it to the template, and also pass that through to the /download page, which can show the latest version, and provide the link to download it - and also wants some updating to link to Dancer2 first, then mention Dancer1 as a "we recommend you don't use this for new apps, but Dancer is still available ...".

**Comment by cromedome** [comment]
#69 resolves this.

**Comment by cromedome** [comment]
Merged fix to master, closing.
